/** BiciMarket demo v3 - Payments App seed. Copy to `prisma/seed.ts`. */
import { createHash } from 'node:crypto'
import { PrismaClient } from '../src/generated/prisma/client'

const SCENARIO = 'bicimarket-demo-v3'
const ORDER_COUNT = 2400
const BATCH_SIZE = Math.max(50, Number(process.env.SEED_BATCH_SIZE ?? 500))
type PaymentState = 'pending' | 'approved' | 'rejected' | 'cancelled' | 'refunded'
type ShipmentState = 'created' | 'ready_for_pickup' | 'picked_up' | 'in_transit' | 'out_for_delivery' | 'delivered' | 'failed_delivery' | 'returned'
type Service = 'standard' | 'express' | 'same_day'
type Postal = { cp: string; lat: number; lng: number; city: string; province: string }
const POSTALS: Postal[] = [
  { cp: 'C1043', lat: -34.6037, lng: -58.4044, city: 'Almagro', province: 'Buenos Aires' }, { cp: 'C1406', lat: -34.6190, lng: -58.4427, city: 'Caballito', province: 'Buenos Aires' },
  { cp: 'C1425', lat: -34.5895, lng: -58.4222, city: 'Palermo', province: 'Buenos Aires' }, { cp: 'C1426', lat: -34.5810, lng: -58.4380, city: 'Palermo', province: 'Buenos Aires' },
  { cp: 'B1642', lat: -34.4690, lng: -58.5180, city: 'San Isidro', province: 'Buenos Aires' }, { cp: 'B1629', lat: -34.4580, lng: -58.9070, city: 'Pilar', province: 'Buenos Aires' },
  { cp: 'B1878', lat: -34.7170, lng: -58.2580, city: 'Quilmes', province: 'Buenos Aires' }, { cp: 'B1900', lat: -34.9214, lng: -57.9544, city: 'La Plata', province: 'Buenos Aires' },
  { cp: 'B8000', lat: -38.7196, lng: -62.2724, city: 'Bahía Blanca', province: 'Buenos Aires' }, { cp: 'B7600', lat: -38.0055, lng: -57.5426, city: 'Mar del Plata', province: 'Buenos Aires' },
  { cp: 'S2000', lat: -32.9587, lng: -60.6930, city: 'Rosario', province: 'Santa Fe' }, { cp: 'X5000', lat: -31.4201, lng: -64.1888, city: 'Córdoba', province: 'Córdoba' },
  { cp: 'M5500', lat: -32.8908, lng: -68.8272, city: 'Mendoza', province: 'Mendoza' }, { cp: 'T4000', lat: -26.8083, lng: -65.2176, city: 'San Miguel de Tucumán', province: 'Tucumán' },
  { cp: 'A4400', lat: -24.7821, lng: -65.4232, city: 'Salta', province: 'Salta' }, { cp: 'E3100', lat: -31.7333, lng: -60.5290, city: 'Paraná', province: 'Entre Ríos' },
  { cp: 'N3300', lat: -27.3621, lng: -55.9007, city: 'Posadas', province: 'Misiones' }, { cp: 'Q8300', lat: -38.9516, lng: -68.0591, city: 'Neuquén', province: 'Neuquén' },
  { cp: 'R8400', lat: -41.1335, lng: -71.3103, city: 'San Carlos de Bariloche', province: 'Río Negro' }, { cp: 'U9000', lat: -45.8651, lng: -67.4980, city: 'Comodoro Rivadavia', province: 'Chubut' },
]
const CATALOG = [
  { price: 82_000_000, step: 3_100_000, weight: 13_200, weightStep: 180, products: 'Trek Marlin 5|Specialized Rockhopper|Venzo Raptor|Vairo XR 3.0|Scott Aspect 930|Cannondale Trail 5|Giant Talon 1|Merida Big Nine 300|GT Avalanche Comp|Zenith Cima 29'.split('|') },
  { price: 96_000_000, step: 4_200_000, weight: 7_900, weightStep: 120, products: 'Venzo R35|Trek Domane AL 2|Specialized Allez|Giant Contend AR|Cannondale CAAD13|Scott Speedster 20|Merida Scultura 400|Bianchi Via Nirone|Orbea Avant H40|Wilier GTR Team'.split('|') },
  { price: 52_000_000, step: 2_300_000, weight: 11_500, weightStep: 190, products: 'Raleigh Classic Urban|Raleigh P20 Folding|Olmo Amsterdam|Vairo Metro 1.0|Giant Escape 3|Trek FX 1|Specialized Sirrus 2.0|Cannondale Quick 5|Volta E-Bike City|Aurora Classic 26'.split('|') },
  { price: 31_000_000, step: 1_700_000, weight: 7_800, weightStep: 210, products: 'Firebird Explorer 12|Firebird Explorer 16|Firebird Explorer 20|Vairo Kids 16|Vairo Kids 20|Trek Precaliber 16|Trek Precaliber 20|Specialized Jett 20|Giant XTC Jr 20|Cannondale Kids Trail 20'.split('|') },
  { price: 48_000_000, step: 2_600_000, weight: 10_500, weightStep: 150, products: 'GT Performer 20|Sunday Primer|WeThePeople Arcade|Mongoose Legion L20|Mongoose Legion L40|Haro Downtown|Fit PRK|Cult Gateway|Kink Curb|Subrosa Tiro'.split('|') },
  { price: 5_500_000, step: 1_350_000, weight: 420, weightStep: 210, products: 'Shimano Deore M6100 Cassette|Shimano SLX M7100 Derailleur|Shimano XT M8100 Crankset|Shimano MT200 Brakes|SRAM GX Eagle Cassette|Fox 36 Float Factory|Continental Race King 29|Fizik Antares R1|DT Swiss M1900 Wheelset|Shimano PD-M520 Pedals'.split('|') },
  { price: 2_800_000, step: 850_000, weight: 250, weightStep: 170, products: 'Specialized Align II MIPS Helmet|Abus Bordo 6000 Lock|Lezyne Macro Drive 1200 Light|CamelBak MULE Backpack|Topeak JoeBlow Pump|Garmin Edge 530 Computer|Thule ProRide Rack|Fidlock Twist Bottle|Topeak Wedge Saddle Bag|Park Tool PCS-10 Stand'.split('|') },
  { price: 3_200_000, step: 720_000, weight: 180, weightStep: 55, products: 'Fox Ranger Jersey|Fox Ranger Shorts|Castelli Rosso Corsa Bib|Castelli Perfetto Jacket|Giro Bravo Gel Gloves|Shimano XC501 Shoes|Shimano RC502 Shoes|Oakley Sutro Glasses|Craft Active Base Layer|Endura Hummvee Pants'.split('|') },
] as const
function listingProduct(seller: number, slot: number) { const category = CATALOG[slot - 1], baseIndex = ((seller - 1) + (slot - 1) * 3) % 10, title = category.products[baseIndex].replace('Giant XTC Jr 20', 'Giant XTC Junior 20'); return { title, price: category.price + baseIndex * category.step + seller * 125_000, weight: category.weight + baseIndex * category.weightStep } }
function hash(text: string): number { let v = 2166136261; for (let i = 0; i < text.length; i++) { v ^= text.charCodeAt(i); v = Math.imul(v, 16777619) } return v >>> 0 }
function int(key: string, max: number): number { return hash(`${SCENARIO}:${key}`) % max }
function pad(n: number, size: number): string { return String(n).padStart(size, '0') }
function addDays(d: Date, n: number): Date { const x = new Date(d); x.setUTCDate(x.getUTCDate() + n); return x }
function addHours(d: Date, n: number): Date { const x = new Date(d); x.setUTCHours(x.getUTCHours() + n); return x }
function minDate(a: Date, b: Date): Date { return a < b ? a : b }
function requireAnchor(): Date { const raw = process.env.SEED_ANCHOR_DATE; if (!raw || !/^\d{4}-\d{2}-\d{2}$/.test(raw)) throw new Error('SEED_ANCHOR_DATE=YYYY-MM-DD is required'); const d = new Date(`${raw}T00:00:00Z`); if (Number.isNaN(d.getTime())) throw new Error('Invalid SEED_ANCHOR_DATE'); return d }
const ANCHOR = requireAnchor(); const START = addDays(ANCHOR, -730)
const buyerId = (n: number) => `byp_demo_${pad(n, 4)}`; const buyerClerkId = (n: number) => `user_buyer_demo_${pad(n, 4)}`; const sellerId = (n: number) => `slp_demo_${pad(n, 3)}`
const productId = (s: number, p: number) => `prd_demo_${pad(s, 3)}_${pad(p, 2)}`; const orderId = (n: number) => `ord_demo_${pad(n, 5)}`; const paymentId = (n: number) => `pay_demo_${pad(n, 5)}`
const groupId = (o: number, s: number) => `osg_demo_${pad(o, 5)}_${pad(s, 3)}`; const salesOrderId = (o: number, s: number) => `sor_demo_${pad(o, 5)}_${pad(s, 3)}`; const quoteId = (o: number, s: number) => `qte_demo_${pad(o, 5)}_${pad(s, 3)}`; const shipmentId = (o: number, s: number) => `shp_demo_${pad(o, 5)}_${pad(s, 3)}`
function buyerAssignments(): number[] { const r = Array<number>(ORDER_COUNT + 1).fill(0), used = new Set<number>(); for (let k = 0; k < 130; k++) { const p = Math.floor((k + .5) * 2055 / 130) + 1; used.add(p); r[p] = 51 + k } for (let k = 0; k < 120; k++) { const p = 2056 + Math.floor((k + .5) * 345 / 120); used.add(p); r[p] = 181 + k } const recent = Array.from({ length: 345 }, (_, i) => 2056 + i).filter(i => !used.has(i)); for (let n = 0; n < 200; n++) { const s = int(`recent-repeat-slot:${n}`, recent.length), p = recent.splice(s, 1)[0]; used.add(p); r[p] = 301 + n } const a = Array.from({ length: ORDER_COUNT }, (_, i) => i + 1).filter(i => !used.has(i)); for (let n = 0; n < 200; n++) { const s = int(`repeat-slot:${n}`, a.length); r[a.splice(s, 1)[0]] = 301 + n } for (const p of a) r[p] = 301 + int(`buyer:${p}`, 200); return r }
const BUYER_BY_ORDER = buyerAssignments()
function orderDate(n: number): Date { const day = n <= 1000 ? Math.floor((n - 1) * 365 / 1000) : 365 + Math.floor((n - 1001) * 365 / 1400), d = addDays(START, day); d.setUTCHours(8 + int(`hour:${n}`, 14), int(`minute:${n}`, 60)); return d }
function paymentState(n: number): PaymentState { const b = n * 37 % 100; return b < 92 ? 'approved' : b < 95 ? 'rejected' : b < 97 ? 'pending' : b < 99 ? 'cancelled' : 'refunded' }
function groupCount(n: number): number { const r = int(`groups:${n}`, 100); return r < 72 ? 1 : r < 95 ? 2 : 3 }
function buyerPostal(n: number): Postal { const p = int(`buyer-zone:${n}`, 100) < 55 ? POSTALS.slice(0, 8) : POSTALS; return p[int(`buyer-postal:${n}`, p.length)] }
function sellerPostal(n: number): Postal { return POSTALS[n * 7 % POSTALS.length] }
function distance(a: Postal, b: Postal): number { const rad = (v: number) => v * Math.PI / 180, la = rad(b.lat - a.lat), lo = rad(b.lng - a.lng), q = Math.sin(la / 2) ** 2 + Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(lo / 2) ** 2; return Math.round(12742 * Math.atan2(Math.sqrt(q), Math.sqrt(1 - q))) }
function shipmentState(n: number, g: number, state: PaymentState, age: number): ShipmentState | null { if (state === 'pending' || state === 'rejected' || state === 'cancelled') return null; const r = int(`shipment-state:${n}:${g}`, 100); if (state === 'refunded') return r < 25 ? null : r < 62 ? 'returned' : 'failed_delivery'; if (age <= 2) return r < 30 ? null : r < 55 ? 'created' : r < 80 ? 'ready_for_pickup' : r < 95 ? 'picked_up' : 'in_transit'; if (age <= 5) return r < 10 ? 'created' : r < 30 ? 'ready_for_pickup' : r < 55 ? 'picked_up' : r < 85 ? 'in_transit' : r < 95 ? 'out_for_delivery' : 'delivered'; if (age <= 9) return r < 5 ? 'ready_for_pickup' : r < 15 ? 'picked_up' : r < 40 ? 'in_transit' : r < 65 ? 'out_for_delivery' : r < 95 ? 'delivered' : r < 98 ? 'failed_delivery' : 'returned'; return r < 82 ? 'delivered' : r < 86 ? 'in_transit' : r < 89 ? 'out_for_delivery' : r < 92 ? 'ready_for_pickup' : r < 94 ? 'picked_up' : r < 97 ? 'failed_delivery' : r < 99 ? 'returned' : 'created' }
type Item = { productId: string; name: string; price: number; quantity: number; weight: number }
type Group = { seller: number; id: string; salesOrderId: string; quoteId: string; shipmentId: string; items: Item[]; subtotal: number; weight: number; shippingCost: number; service: Service; shipmentStatus: ShipmentState | null; shipmentCreatedAt: Date | null; deliveredAt: Date | null }
type Order = { n: number; id: string; buyer: number; createdAt: Date; payment: PaymentState; groups: Group[]; total: number }
function settlementStatus(order: Order, group: Group): 'pending' | 'paid' | 'failed' | 'manual_review' | null { if (!group.deliveredAt) return null; const age = Math.floor((ANCHOR.getTime() - group.deliveredAt.getTime()) / 86_400_000), r = int(`settlement:${order.n}:${group.seller}`, 100); return age <= 7 ? r < 55 ? 'paid' : r < 90 ? 'pending' : r < 95 ? 'failed' : 'manual_review' : r < 78 ? 'paid' : r < 90 ? 'pending' : r < 95 ? 'failed' : 'manual_review' }
function makeOrder(n: number): Order {
  const buyer = BUYER_BY_ORDER[n], createdAt = orderDate(n), payment = paymentState(n), groups: Group[] = [], used = new Set<number>()
  for (let g = 0; g < groupCount(n); g++) {
    let seller = 1 + (int(`seller:${n}`, 32) + g * 11) % 32
    while (used.has(seller)) seller = seller % 32 + 1
    used.add(seller)
    const items: Item[] = [], slots = new Set<number>(), count = 1 + int(`item-count:${n}:${g}`, 3)
    for (let j = 0; j < count; j++) {
      let slot = 1 + ((int(`item-slot:${n}:${g}`, 8) + j * 3) % 8)
      while (slots.has(slot)) slot = slot % 8 + 1
      slots.add(slot)
      const p = listingProduct(seller, slot)
      items.push({ productId: productId(seller, slot), name: p.title, price: p.price, quantity: int(`quantity:${n}:${g}:${j}`, 100) < 18 ? 2 : 1, weight: p.weight })
    }
    const subtotal = items.reduce((s, x) => s + x.price * x.quantity, 0), weight = items.reduce((s, x) => s + x.weight * x.quantity, 0), km = distance(sellerPostal(seller), buyerPostal(buyer))
    const service: Service = km <= 50 && int(`service:${n}:${g}`, 100) < 25 ? 'same_day' : km <= 700 && int(`service:${n}:${g}`, 100) < 45 ? 'express' : 'standard'
    const base = service === 'same_day' ? 3_000_000 : service === 'express' ? 1_500_000 : 800_000, shippingCost = base + Math.min(km, 5000) * 1000 + Math.ceil(weight / 1000) * 20_000
    const age = Math.floor((ANCHOR.getTime() - createdAt.getTime()) / 86_400_000)
    let status = shipmentState(n, g, payment, age)
    const shipped = status ? minDate(addDays(createdAt, 1 + int(`ship-delay:${n}:${g}`, 3)), addHours(ANCHOR, -1)) : null, eta = service === 'same_day' ? 1 : service === 'express' ? 3 : 6
    let delivered = status === 'delivered' && shipped ? addDays(shipped, 1 + int(`delivery-days:${n}:${g}`, eta)) : null
    if (delivered && delivered >= ANCHOR) { delivered = null; status = 'out_for_delivery' }
    groups.push({ seller, id: groupId(n, seller), salesOrderId: salesOrderId(n, seller), quoteId: quoteId(n, seller), shipmentId: shipmentId(n, seller), items, subtotal, weight, shippingCost, service, shipmentStatus: status, shipmentCreatedAt: shipped, deliveredAt: delivered })
  }
  return { n, id: orderId(n), buyer, createdAt, payment, groups, total: groups.reduce((s, group) => s + group.subtotal + group.shippingCost, 0) }
}
function method(n: number): 'credit_card' | 'debit_card' | 'account_money' | 'bank_transfer' | 'pix' { const r = int(`method:${n}`, 100); return r < 35 ? 'credit_card' : r < 60 ? 'debit_card' : r < 80 ? 'account_money' : r < 95 ? 'bank_transfer' : 'pix' }
async function createMany(model: { createMany(args: any): Promise<any> }, data: any[]) { for (let i = 0; i < data.length; i += BATCH_SIZE) await model.createMany({ data: data.slice(i, i + BATCH_SIZE) }) }
function fingerprint(orders: Order[]): string { const canonical = orders.flatMap(o => [o.id, buyerId(o.buyer), paymentId(o.n), o.payment, ...o.groups.flatMap(g => [g.id, g.salesOrderId, g.quoteId, g.shipmentId, String(g.subtotal), String(g.shippingCost), String(g.shipmentStatus), ...g.items.map(i => i.productId)])]).join('|'); return createHash('sha256').update(canonical).digest('hex') }

async function main() {
  const orders = Array.from({ length: ORDER_COUNT }, (_, i) => makeOrder(i + 1)), fp = fingerprint(orders), delivered = orders.flatMap(order => order.groups.filter(g => g.deliveredAt).map(group => ({ order, group })))
  const statusCounts = Object.fromEntries(['approved', 'pending', 'rejected', 'cancelled', 'refunded'].map(s => [s, orders.filter(o => o.payment === s).length]))
  console.log({ scenario: SCENARIO, anchor: ANCHOR.toISOString(), payments: orders.length, settlements: delivered.length, statuses: statusCounts, fingerprint: fp })
  if (process.env.SEED_DRY_RUN === '1') return
  if (process.env.SEED_ALLOW_RESET !== 'BICIMARKET_DEMO') throw new Error('Refusing reset: set SEED_ALLOW_RESET=BICIMARKET_DEMO')
  const prisma = new PrismaClient()
  try {
    await prisma.outboundCallLog.deleteMany(); await prisma.webhookJob.deleteMany(); await prisma.mpWebhookEvent.deleteMany(); await prisma.refundStatusHistory.deleteMany(); await prisma.refund.deleteMany(); await prisma.payout.deleteMany(); await prisma.settlementStatusHistory.deleteMany(); await prisma.settlement.deleteMany(); await prisma.receipt.deleteMany(); await prisma.paymentAttempt.deleteMany(); await prisma.paymentStatusHistory.deleteMany(); await prisma.payment.deleteMany()
    await createMany(prisma.payment, orders.map(o => { const m = method(o.n), final = o.payment === 'approved' || o.payment === 'refunded', hasMethod = o.payment !== 'pending' && o.payment !== 'cancelled'; return { id: paymentId(o.n), order_id: o.id, buyer_profile_id: buyerId(o.buyer), buyer_clerk_user_id: buyerClerkId(o.buyer), amount_cents: o.total, currency: 'ARS', status: o.payment, ...(hasMethod ? { method: m } : {}), ...(hasMethod && (m === 'credit_card' || m === 'debit_card') ? { card_last4: pad(1000 + int(`last4:${o.n}`, 8999), 4) } : {}), ...(o.payment !== 'pending' && o.payment !== 'cancelled' ? { gateway_reference: `mp_demo_${pad(o.n, 8)}` } : {}), items_summary: final ? o.groups.map(g => ({ seller_profile_id: sellerId(g.seller), subtotal_cents: g.subtotal, shipping_cost_cents: g.shippingCost, order_seller_group_id: g.id, items: g.items.map(i => ({ product_id: i.productId, product_name_snapshot: i.name, unit_price_cents: i.price, quantity: i.quantity })) })) : undefined, idempotency_key: `seed:${SCENARIO}:payment:${o.n}`, checkout_url: final ? `https://mercadopago.test/checkout/${paymentId(o.n)}` : null, preference_id: final ? `pref_demo_${pad(o.n, 6)}` : null, approved_at: final ? addHours(o.createdAt, 2) : null, rejected_at: o.payment === 'rejected' ? addHours(o.createdAt, 1) : null, cancelled_at: o.payment === 'cancelled' ? addHours(o.createdAt, 1) : null, created_at: o.createdAt, updated_at: o.createdAt, deleted_at: null } }) as any[])
    const paymentHistory: any[] = [], attempts: any[] = [], receipts: any[] = []
    for (const o of orders) {
      const transitions: Array<[PaymentState | null, PaymentState, string]> = [[null, 'pending', 'payment_created']]
      if (o.payment === 'approved') transitions.push(['pending', 'approved', 'gateway_approved'])
      if (o.payment === 'rejected') transitions.push(['pending', 'rejected', 'gateway_rejected'])
      if (o.payment === 'cancelled') transitions.push(['pending', 'cancelled', 'buyer_cancelled_checkout'])
      if (o.payment === 'refunded') { transitions.push(['pending', 'approved', 'gateway_approved']); transitions.push(['approved', 'refunded', 'full_refund_processed']) }
      transitions.forEach(([from, to, reason], i) => paymentHistory.push({ id: `psh_demo_${pad(o.n, 5)}_${i + 1}`, payment_id: paymentId(o.n), from_status: from, to_status: to, changed_by: 'system', reason, created_at: addHours(o.createdAt, i * 2) }))
      const retry = o.payment === 'approved' && int(`retry:${o.n}`, 100) < 8
      if (retry) attempts.push({ id: `pat_demo_${pad(o.n, 5)}_1`, payment_id: paymentId(o.n), attempt_number: 1, provider: 'mercadopago', status: 'rejected', error_code: 'cc_rejected_insufficient_amount', error_message: 'Fondos insuficientes en el primer intento', request_payload: { order_id: o.id }, response_payload: { status_detail: 'cc_rejected_insufficient_amount' }, created_at: o.createdAt })
      const attemptsCount = o.payment === 'rejected' ? 1 + int(`attempts:${o.n}`, 3) : 1
      for (let a = 0; a < attemptsCount; a++) attempts.push({ id: `pat_demo_${pad(o.n, 5)}_${a + 1 + (retry ? 1 : 0)}`, payment_id: paymentId(o.n), attempt_number: a + 1 + (retry ? 1 : 0), provider: 'mercadopago', status: o.payment === 'refunded' ? 'approved' : o.payment, error_code: o.payment === 'rejected' ? ['cc_rejected_card_disabled', 'cc_rejected_insufficient_amount', 'cc_rejected_other_reason'][a % 3] : null, error_message: o.payment === 'rejected' ? 'Pago rechazado por el gateway' : null, request_payload: { order_id: o.id, amount_cents: o.total }, response_payload: { status: o.payment }, created_at: addHours(o.createdAt, a + 1) })
      if (o.payment === 'approved' || o.payment === 'refunded') receipts.push({ id: `rcp_demo_${pad(o.n, 5)}`, payment_id: paymentId(o.n), receipt_number: `RCP-DEMO-${pad(o.n, 7)}`, receipt_url: `https://payments.bicimarket.test/receipts/${paymentId(o.n)}.pdf`, amount_cents: o.total, idempotency_key: `seed:${SCENARIO}:receipt:${o.n}`, issued_at: addHours(o.createdAt, 3), created_at: addHours(o.createdAt, 3), deleted_at: null })
    }
    await createMany(prisma.paymentStatusHistory, paymentHistory); await createMany(prisma.paymentAttempt, attempts as any[]); await createMany(prisma.receipt, receipts)
    const settlements = delivered.map(({ order, group }) => { const status = settlementStatus(order, group)!; const gross = group.subtotal, fee = Math.round(gross * .1), created = group.deliveredAt!; return { id: `set_demo_${pad(order.n, 5)}_${pad(group.seller, 3)}`, payment_id: paymentId(order.n), order_id: order.id, order_seller_group_id: group.id, sales_order_id: group.salesOrderId, seller_profile_id: sellerId(group.seller), shipment_id: group.shipmentId, delivered_at: created, gross_amount_cents: gross, fee_amount_cents: fee, net_amount_cents: gross - fee, currency: 'ARS', status, paid_at: status === 'paid' ? minDate(addDays(created, 2), addHours(ANCHOR, -1)) : null, created_at: created, updated_at: created, deleted_at: null, _order: order, _group: group } })
    await createMany(prisma.settlement, settlements.map(({ _order, _group, ...s }) => s) as any[])
    const settlementHistory = settlements.flatMap(s => { const rows: any[] = [{ id: `sth_${s.id}_1`, settlement_id: s.id, from_status: null, to_status: 'pending', changed_by: 'system', reason: 'shipment_delivered', created_at: s.created_at }]; if (s.status !== 'pending') rows.push({ id: `sth_${s.id}_2`, settlement_id: s.id, from_status: 'pending', to_status: s.status, changed_by: 'system', reason: s.status === 'paid' ? 'payout_processed' : s.status === 'failed' ? 'payout_failed' : 'requires_manual_review', created_at: minDate(addDays(s.created_at, 1), addHours(ANCHOR, -1)) }); return rows })
    await createMany(prisma.settlementStatusHistory, settlementHistory)
    const paidSettlements = settlements.filter(s => s.status === 'paid')
    await createMany(prisma.payout, paidSettlements.map(s => { const r = int(`payout:${s.id}`, 100), status = r < 92 ? 'completed' : r < 95 ? 'failed' : r < 97 ? 'pending' : r < 99 ? 'in_progress' : 'manual_review'; return { id: `pot_${s.id}`, settlement_id: s.id, transfer_id: status === 'completed' ? `trf_demo_${s.id}` : null, status, attempts: status === 'completed' ? 1 : status === 'failed' ? 3 : status === 'pending' ? 0 : 2, last_error: status === 'failed' ? 'Transferencia rechazada por collector_id inválido' : status === 'manual_review' ? 'Cuenta bancaria requiere revisión' : null, idempotency_key: `seed:${SCENARIO}:payout:${s.id}`, started_at: status === 'pending' ? null : minDate(addDays(s.created_at, 1), addHours(ANCHOR, -1)), completed_at: status === 'completed' ? minDate(addDays(s.created_at, 2), addHours(ANCHOR, -1)) : null, created_at: s.created_at, updated_at: s.created_at, deleted_at: null } }))
    const refundable = orders.filter(o => o.payment === 'refunded' || o.groups.some(g => g.shipmentStatus === 'returned' || g.shipmentStatus === 'failed_delivery') || (o.payment === 'approved' && int(`partial-refund:${o.n}`, 100) < 4))
    const refunds = refundable.map(o => { const full = o.payment === 'refunded', incidentGroup = o.groups.find(g => g.shipmentStatus === 'returned' || g.shipmentStatus === 'failed_delivery'), group = incidentGroup ?? o.groups[int(`refund-group:${o.n}`, o.groups.length)], r = int(`refund-status:${o.n}`, 100), status = r < 80 ? 'approved' : r < 90 ? 'pending' : 'failed', rr = int(`refund-reason:${o.n}`, 100), reason = incidentGroup ? 'not_delivered' : rr < 30 ? 'seller_rejected' : rr < 60 ? 'buyer_cancelled' : rr < 85 ? 'not_delivered' : 'manual', amount = full ? o.total : Math.min(group.subtotal, Math.round(group.subtotal * (20 + int(`refund-percent:${o.n}`, 31)) / 100)), created = minDate(addDays(o.createdAt, 3 + int(`refund-delay:${o.n}`, 8)), addHours(ANCHOR, -1)); return { id: `ref_demo_${pad(o.n, 5)}`, payment_id: paymentId(o.n), seller_profile_id: full ? null : sellerId(group.seller), amount_cents: amount, currency: 'ARS', reason, status, gateway_reference: status === 'approved' ? `mp_refund_demo_${pad(o.n, 6)}` : null, idempotency_key: `seed:${SCENARIO}:refund:${o.n}`, created_at: created, updated_at: created, deleted_at: null } })
    await createMany(prisma.refund, refunds as any[])
    await createMany(prisma.refundStatusHistory, refunds.flatMap(r => { const rows: any[] = [{ id: `rfh_${r.id}_1`, refund_id: r.id, from_status: null, to_status: 'pending', changed_by: 'system', reason: 'refund_requested', created_at: r.created_at }]; if (r.status !== 'pending') rows.push({ id: `rfh_${r.id}_2`, refund_id: r.id, from_status: 'pending', to_status: r.status, changed_by: 'system', reason: r.status === 'approved' ? 'refund_processed' : 'refund_gateway_error', created_at: minDate(addHours(r.created_at, 8), addHours(ANCHOR, -1)) }); return rows }))
    const events = orders.map(o => { const r = int(`webhook:${o.n}`, 100), status = r < 2 ? 'failed' : r < 4 ? 'processing' : 'processed'; return { id: `mwe_demo_${pad(o.n, 5)}`, mp_event_id: `mp_evt_demo_${pad(o.n, 7)}`, event_type: `payment.${o.payment}`, payload: { action: `payment.${o.payment}`, data: { id: `mp_demo_${pad(o.n, 8)}` }, order_id: o.id }, signature_valid: status !== 'failed', processed_at: status === 'processed' ? addHours(o.createdAt, 3) : null, last_error: status === 'failed' ? 'HMAC signature mismatch' : status === 'processing' ? 'Gateway timeout, retry scheduled' : null, status, created_at: addHours(o.createdAt, 2), _order: o } })
    await createMany(prisma.mpWebhookEvent, events.map(({ _order, ...e }) => e) as any[])
    const jobs: any[] = []
    for (const event of events) { const o = event._order; jobs.push({ id: `whj_demo_${pad(o.n, 5)}_process`, mp_event_id: event.mp_event_id, job_type: 'process_webhook', payload: { payment_id: paymentId(o.n), order_id: o.id }, status: event.status === 'processed' ? 'completed' : event.status, attempts: event.status === 'failed' ? 10 : event.status === 'processing' ? 2 : 1, max_attempts: 10, last_error: event.last_error, scheduled_at: event.created_at, created_at: event.created_at, updated_at: event.created_at }); if (o.payment === 'approved' || o.payment === 'refunded') { jobs.push({ id: `whj_demo_${pad(o.n, 5)}_buyer`, mp_event_id: event.mp_event_id, job_type: 'send_notification', payload: { target: 'buyer', order_id: o.id, payment_id: paymentId(o.n) }, status: 'completed', attempts: 1, max_attempts: 10, last_error: null, scheduled_at: addHours(event.created_at, 1), created_at: addHours(event.created_at, 1), updated_at: addHours(event.created_at, 1) }); for (const g of o.groups) jobs.push({ id: `whj_demo_${pad(o.n, 5)}_seller_${pad(g.seller, 3)}`, mp_event_id: event.mp_event_id, job_type: 'send_notification', payload: { target: 'seller', sales_order_id: g.salesOrderId, seller_profile_id: sellerId(g.seller) }, status: 'completed', attempts: 1, max_attempts: 10, last_error: null, scheduled_at: addHours(event.created_at, 1), created_at: addHours(event.created_at, 1), updated_at: addHours(event.created_at, 1) }) } }
    await createMany(prisma.webhookJob, jobs as any[])
    const outbound = orders.filter(o => o.n % 2 === 0).map(o => { const success = int(`outbound:${o.n}`, 100) >= 10; return { id: `ocl_demo_${pad(o.n, 5)}`, target_app: ['buyer', 'seller', 'shipping'][int(`target:${o.n}`, 3)], method: o.n % 3 ? 'POST' : 'PATCH', path: o.n % 3 === 0 ? '/api/v1/internal/shipment-delivered' : o.n % 2 === 0 ? '/api/v1/orders/{id}/status' : '/api/v1/sales-orders/{id}/payment-status', request_body: { order_id: o.id, payment_id: paymentId(o.n) }, response_status: success ? 200 : null, response_body: success ? { ok: true } : { error: 'timeout' }, attempts: success ? 1 : 3, last_error: success ? null : 'Connection timeout after 3 retries', succeeded_at: success ? addHours(o.createdAt, 4) : null, created_at: addHours(o.createdAt, 3) } })
    await createMany(prisma.outboundCallLog, outbound as any[])
    console.log('Payments seed complete', { payments: await prisma.payment.count(), settlements: await prisma.settlement.count(), refunds: await prisma.refund.count(), payouts: await prisma.payout.count(), fingerprint: fp })
  } finally { await prisma.$disconnect() }
}
main().catch(error => { console.error('Payments seed failed', error); process.exit(1) })
